### PR TITLE
WIP Graphite 1.0

### PR DESCRIPTION
**Pull request by obfuscurity**
This PR tracks the [feature/graphite-master](https://github.com/obfuscurity/synthesize/tree/feature/graphite-master) branch as we follow Graphite `HEAD` towards its _inevitable_ 1.0 release.

### CODE REVIEW

**Comment by obfuscurity** [comment]
fixes #18 and #45

**Comment by obfuscurity** [comment]
cc @deniszh

**Comment by deniszh** [comment]
Ah, OK

**Comment by obfuscurity** [comment]
Tested locally with Vagrant, LGTM.

**Comment by obfuscurity** [comment]
Published Synthesize [3.0.0](https://github.com/obfuscurity/synthesize/releases/tag/v3.0.0) to support Graphite 1.0.0.

**Pull request merged**
